site_name: AWS OBSERVABILITY WORKSHOP
site_description: A workshop to learn about AWS Observability services and best practices.
site_author: Pablo

theme:
  name: material
  palette:
    # Dark Mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Light Mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - Introduction:
    - Introduction to AWS Observability: "00-aws_observability.md"
    - Observability with Amazon CloudWatch: "00-observability_with_amazon_cloudwatch.md"
    - What you'll learn: "01-learn.md"
    - Application architecture: "02-application_architecture.md"
    - Using the CloudFormation console: "03-cloudformation_console.md"
    - Workshop pre-requisites: "04-workshop_pre-requisites.md"
  - Log Management:
    - Logs and Log Management: "05-logs_and_log_management.md"
    - CloudWatch Logs and log groups: "06-cloudwatch_logs_and_log_groups.md"
  - Data Ingestion:
    - Ingestion - data sources: "07-ingestion-data_sources.md"
    - Ingestion - enablement rules: "08-ingestion-enablement_rules.md"
    - Ingestion - telemetry pipelines: "09-ingestion-telemetry_pipelines.md"

